### ISSUE TITLE
HelloWorld fails on WSL1/Ubuntu distribution

### ISSUE THREAD

**Issue by MaherJendoubi** [microsoft/InnerEye-DeepLearning#248]
(InnerEye) maher@PC:~/InnerEye-DeepLearning$ **python InnerEye/ML/runner.py --model=HelloWorld**
Setting up logging to stdout.
Setting logging level to 20
2020-09-25T13:50:35Z INFO     rpdb is handling traps. To debug: identify the main runner.py process, then as root: kill -TRAP <process_id>; nc 127.0.0.1 4444
2020-09-25T13:50:37Z INFO     Found class HelloWorld in file /home/maher/InnerEye-DeepLearning/InnerEye/ML/configs/segmentation/HelloWorld.py
2020-09-25T13:50:37Z INFO     Creating the default output folder structure.
2020-09-25T13:50:37Z INFO     Running outside of AzureML.
2020-09-25T13:50:37Z INFO     All results will be written to a subfolder of the project root folder.
2020-09-25T13:50:37Z INFO     Run outputs folder: /home/maher/InnerEye-DeepLearning/outputs/2020-09-25T135037Z_HelloWorld
2020-09-25T13:50:37Z INFO     Logs folder: /home/maher/InnerEye-DeepLearning/outputs/2020-09-25T135037Z_HelloWorld/logs
2020-09-25T13:50:37Z INFO     Creating the adjusted output folder structure.
2020-09-25T13:50:37Z INFO     Running outside of AzureML.
2020-09-25T13:50:37Z INFO     All results will be written to a subfolder of the project root folder.
2020-09-25T13:50:37Z INFO     Run outputs folder: /home/maher/InnerEye-DeepLearning/outputs/2020-09-25T135037Z_HelloWorld
2020-09-25T13:50:37Z INFO     Logs folder: /home/maher/InnerEye-DeepLearning/outputs/2020-09-25T135037Z_HelloWorld/logs
2020-09-25T13:50:37Z INFO     extra_code_directory is unset
Setting logging level to 20
Setting up logging with level 20 to file /home/maher/InnerEye-DeepLearning/outputs/2020-09-25T135037Z_HelloWorld/logs/stdout.txt
2020-09-25T13:50:47Z INFO     Setting multiprocessing start method to 'forkserver'
2020-09-25T13:50:47Z INFO     Model training will use the local dataset provided in /home/maher/InnerEye-DeepLearning/Tests/ML/test_data
2020-09-25T13:50:47Z INFO
Arguments:
        __center_size_param_value: None
        __dataset_data_frame_param_value: None
        __inference_stride_size_param_value: None
        __largest_connected_component_foreground_classes_param_value: None
        __min_l_rate_param_value: 0
        __model_category_param_value: ModelCategory.Segmentation
        __model_name_param_value: HelloWorld
        __overrides_param_value: None
        __use_gpu_param_value: False
        _architecture_param_value: UNet3D
        _class_weights_param_value: [0.02, 0.49, 0.49]
        _colours_param_value: [(130, 183, 14), (238, 127, 26)]
        _comparison_blob_storage_paths_param_value: None
        _crop_size_param_value: (64, 64, 64)
        _datasets_for_inference: None
        _datasets_for_training: None
        _feature_channels_param_value: [4]
        _file_system_config_param_value: <DeepLearningFileSystemConfig DeepLearningFileSystemConfig00010>
        _fill_holes_param_value: [True, True]
        _ground_truth_ids_display_names_param_value: ['region', 'region_1']
        _ground_truth_ids_param_value: ['region', 'region_1']
        _image_channels_param_value: ['channel1', 'channel2']
        _instance__params : {}
        _l_rate_multi_step_milestones_param_value: None
        _level_param_value: 50
        _local_dataset_param_value: /home/maher/InnerEye-DeepLearning/Tests/ML/test_data
        _mask_id_param_value: mask
        _multiprocessing_start_method_param_value: MultiprocessingStartMethod.forkserver
        _name_param_value : HelloWorld00008
        _norm_method_param_value: PhotometricNormalizationMethod.CtWindow
        _num_dataload_workers_param_value: 0
        _num_epochs_param_value: 2
        _param_watchers   : {}
        _save_start_epoch_param_value: 1
        _save_step_epochs_param_value: 1
        _slice_exclusion_rules_param_value: []
        _start_epoch_param_value: 0
        _summed_probability_rules_param_value: []
        _tail_param_value : None
        _test_crop_size_param_value: (64, 64, 64)
        _test_diff_epochs_param_value: 1
        _test_start_epoch_param_value: 2
        _test_step_epochs_param_value: 1
        _train_batch_size_param_value: 2
        _use_mixed_precision_param_value: True
        _window_param_value: 200
        initialized       : True
        param             : <param.parameterized.Parameters object at 0x7fceaeff2ef0>

2020-09-25T13:50:47Z INFO
2020-09-25T13:50:47Z INFO     **** STARTING: Model training **********************************************************************
2020-09-25T13:50:47Z INFO
2020-09-25T13:50:47Z INFO     Train: 3, Test: 1, and Val: 2. Total subjects: 6
2020-09-25T13:50:47Z INFO     Model Training: Random seed set to: 42
2020-09-25T13:50:47Z INFO     Starting to read and parse the datasets.
2020-09-25T13:50:47Z INFO     Processing dataset (name=None)
2020-09-25T13:50:47Z INFO     Processing dataset (name=None)
2020-09-25T13:50:47Z INFO     Creating the data loader for the training set.
2020-09-25T13:50:47Z INFO     Creating the data loader for the validation set.
2020-09-25T13:50:47Z INFO     Finished creating the data loaders.
2020-09-25T13:50:48Z INFO     Models are saved at /home/maher/InnerEye-DeepLearning/outputs/2020-09-25T135037Z_HelloWorld/checkpoints
2020-09-25T13:50:48Z INFO     Writing model summary to: logs/model_summaries/model_log001.txt
Attempted to log scalar metric LoggingColumns.NumTrainableParameters:
506139
2020-09-25T13:50:48Z INFO     Making no adjustments to the model because no GPU was found.
2020-09-25T13:50:50Z INFO     Starting training
2020-09-25T13:50:50Z INFO     Starting epoch 1
2020-09-25T13:50:50Z INFO     Loaded the first minibatch of training data in 0.15 sec.
2020-09-25T13:50:57Z INFO     Epoch 1 training took 6.51 sec of which data loading took 0.21 sec
2020-09-25T13:50:57Z INFO     Model Training: Random seed set to: 42
2020-09-25T13:50:57Z INFO     Loaded the first minibatch of validation data in 0.10 sec.
2020-09-25T13:50:58Z INFO     Epoch 1 validation took 1.69 sec of which data loading took 0.10 sec
2020-09-25T13:50:58Z INFO     Saved model checkpoint for epoch 1 to /home/maher/InnerEye-DeepLearning/outputs/2020-09-25T135037Z_HelloWorld/checkpoints/1_checkpoint.pth.tar
2020-09-25T13:50:58Z INFO     Starting epoch 2
2020-09-25T13:50:59Z INFO     Loaded the first minibatch of training data in 0.11 sec.
2020-09-25T13:51:04Z INFO     Epoch 2 training took 5.88 sec of which data loading took 0.16 sec
2020-09-25T13:51:05Z INFO     Model Training: Random seed set to: 42
2020-09-25T13:51:05Z INFO     Loaded the first minibatch of validation data in 0.11 sec.
2020-09-25T13:51:06Z INFO     Epoch 2 validation took 1.75 sec of which data loading took 0.11 sec
2020-09-25T13:51:06Z INFO     Saved model checkpoint for epoch 2 to /home/maher/InnerEye-DeepLearning/outputs/2020-09-25T135037Z_HelloWorld/checkpoints/2_checkpoint.pth.tar
2020-09-25T13:51:06Z INFO     Finished training
2020-09-25T13:51:06Z INFO
2020-09-25T13:51:06Z INFO     **** FINISHED: Model training after 19.01 seconds **************************************************
2020-09-25T13:51:06Z INFO
Attempted to log scalar metric Train epochs:
2
2020-09-25T13:51:06Z INFO
2020-09-25T13:51:06Z INFO     **** STARTING: Registering default model ***********************************************************
2020-09-25T13:51:06Z INFO
2020-09-25T13:51:06Z WARNING  Not registering a model, because the run has no associated experiment
2020-09-25T13:51:06Z INFO
2020-09-25T13:51:06Z INFO     **** FINISHED: Registering default model after 0.00 seconds ****************************************
2020-09-25T13:51:06Z INFO
2020-09-25T13:51:06Z INFO
2020-09-25T13:51:06Z INFO     **** STARTING: Running default model on test set ***************************************************
2020-09-25T13:51:06Z INFO
2020-09-25T13:51:06Z INFO     Train: 3, Test: 1, and Val: 2. Total subjects: 6
2020-09-25T13:51:06Z INFO     Model Training: Random seed set to: 42
2020-09-25T13:51:06Z INFO     Results directory: /home/maher/InnerEye-DeepLearning/outputs/2020-09-25T135037Z_HelloWorld/epoch_002/Test
2020-09-25T13:51:06Z INFO     Starting evaluation of model HelloWorld on epoch 2 Test set
2020-09-25T13:51:06Z INFO     Processing dataset (name=None)
2020-09-25T13:51:06Z INFO     Processing dataset (name=None)
2020-09-25T13:51:06Z INFO     Processing dataset (name=None)
2020-09-25T13:51:06Z INFO     Loading checkpoint /home/maher/InnerEye-DeepLearning/outputs/2020-09-25T135037Z_HelloWorld/checkpoints/2_checkpoint.pth.tar
2020-09-25T13:51:06Z INFO     Loaded checkpoint (epoch: 2)
2020-09-25T13:51:06Z INFO     Writing model summary to: logs/model_summaries/model_log001.txt
Setting up logging with level 20 to file logs/model_summaries/model_log001.txt
2020-09-25T13:51:07Z INFO     Making no adjustments to the model because no GPU was found.
2020-09-25T13:51:09Z INFO     Predicting for image 1 of 1...
2020-09-25T13:51:09Z INFO     Inference pipeline (0), Predicting patient: 6
OMP: Info #274: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/maher/anaconda3/envs/InnerEye/lib/python3.7/multiprocessing/forkserver.py", line 186, in main
    with socket.socket(socket.AF_UNIX, fileno=listener_fd) as listener, \
  File "/home/maher/anaconda3/envs/InnerEye/lib/python3.7/socket.py", line 151, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
OSError: [Errno 22] Invalid argument: 'protocol'
**2020-09-25T13:51:26Z ERROR    Model training/testing failed. Exception: unexpected EOF
Traceback (most recent call last):
  File "InnerEye/ML/runner.py", line 360, in run_in_situ
    self.create_ml_runner().run()
  File "/home/maher/InnerEye-DeepLearning/InnerEye/ML/run_ml.py", line 318, in run
    best_epoch = self.run_inference_and_register_model(run_recovery, ModelProcessing.DEFAULT)
  File "/home/maher/InnerEye-DeepLearning/InnerEye/ML/run_ml.py", line 340, in run_inference_and_register_model
    test_metrics, val_metrics, _ = self.model_inference_train_and_test(RUN_CONTEXT, run_recovery, model_proc)
  File "/home/maher/InnerEye-DeepLearning/InnerEye/ML/run_ml.py", line 663, in model_inference_train_and_test
    test_metrics = run_model_test(ModelExecutionMode.TEST)
  File "/home/maher/InnerEye-DeepLearning/InnerEye/ML/run_ml.py", line 659, in run_model_test
    return model_test(config, data_split=data_split, run_recovery=run_recovery, model_proc=model_proc)
  File "/home/maher/InnerEye-DeepLearning/InnerEye/ML/model_testing.py", line 72, in model_test
    return segmentation_model_test(config, data_split, run_recovery, model_proc)
  File "/home/maher/InnerEye-DeepLearning/InnerEye/ML/model_testing.py", line 102, in segmentation_model_test
    run_recovery=run_recovery)
  File "/home/maher/InnerEye-DeepLearning/InnerEye/ML/model_testing.py", line 180, in segmentation_model_test_epoch
    with Pool(processes=num_workers) as pool:
  File "/home/maher/anaconda3/envs/InnerEye/lib/python3.7/multiprocessing/context.py", line 119, in Pool
    context=self.get_context())
  File "/home/maher/anaconda3/envs/InnerEye/lib/python3.7/multiprocessing/pool.py", line 176, in __init__
    self._repopulate_pool()
  File "/home/maher/anaconda3/envs/InnerEye/lib/python3.7/multiprocessing/pool.py", line 241, in _repopulate_pool
    w.start()
  File "/home/maher/anaconda3/envs/InnerEye/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/home/maher/anaconda3/envs/InnerEye/lib/python3.7/multiprocessing/context.py", line 291, in _Popen
    return Popen(process_obj)
  File "/home/maher/anaconda3/envs/InnerEye/lib/python3.7/multiprocessing/popen_forkserver.py", line 35, in __init__
    super().__init__(process_obj)
  File "/home/maher/anaconda3/envs/InnerEye/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/home/maher/anaconda3/envs/InnerEye/lib/python3.7/multiprocessing/popen_forkserver.py", line 55, in _launch
    self.pid = forkserver.read_signed(self.sentinel)
  File "/home/maher/anaconda3/envs/InnerEye/lib/python3.7/multiprocessing/forkserver.py", line 312, in read_signed
    raise EOFError('unexpected EOF')
EOFError: unexpected EOF**
(InnerEye) maher@PC:~/InnerEye-DeepLearning$

**Comment by ant0nsc** [comment]
Hi @MaherJendoubi , thanks for reporting. I can't repro on my WSL Ubuntu 18.04, the demo model runs fine to the end. Is the model failing reproducibly on your side?
Comparing my stdout to the one you posted, the only thing I don't see is this bit here:
```
Traceback (most recent call last):
File "", line 1, in
File "/home/maher/anaconda3/envs/InnerEye/lib/python3.7/multiprocessing/forkserver.py", line 186, in main
with socket.socket(socket.AF_UNIX, fileno=listener_fd) as listener,
File "/home/maher/anaconda3/envs/InnerEye/lib/python3.7/socket.py", line 151, in init
_socket.socket.init(self, family, type, proto, fileno)
OSError: [Errno 22] Invalid argument: 'protocol'
```

**Comment by MaherJendoubi** [comment]
Dear @ant0nsc , thanks for the reply. Would you please reproduce it on your WSL Ubuntu 20.04.1 LTS?

![image](https://user-images.githubusercontent.com/1798510/94405244-8d172000-0170-11eb-9193-902631335854.png)

**Comment by ant0nsc** [comment]
Same story. Inside my WSL Ubuntu 20.04 LTS, I created a brandnew conda environment as per the `environment.yml` file, then ran the Helloworld model. All working fine.

**Comment by MaherJendoubi** [comment]
@ant0nsc Thank you for the repro. Is it possible to elaborate on all the steps until you create a brand-new cond environment and specify anaconda/python/Windows OS/WSL versions?

**Comment by ant0nsc** [comment]
I just followed the steps in Readme: `conda env create --file environment.yml`, `conda activate InnerEye`, then "export PYTHONPATH=`pwd`" and then run the model.
If you enter `conda activate InnerEye` and then do `python --version`, what does it say?

**Comment by MaherJendoubi** [comment]
![image](https://user-images.githubusercontent.com/1798510/94413349-40851200-017b-11eb-9941-09de84f888cc.png)

**Comment by MaherJendoubi** [comment]
![image](https://user-images.githubusercontent.com/1798510/94413801-e042a000-017b-11eb-8226-5fc3f632e18b.png)

**Comment by ant0nsc** [comment]
Thanks @Shruthi42 for helping with that. There's an issue opened on WSL https://github.com/microsoft/WSL/issues/4604, that shows the sockets issue in your stdout. However, those issues are reported on WSL1, and marked as "resolved in WSL2". Can you confirm that you are using WSL2?

**Comment by MaherJendoubi** [comment]
My bad, I still using WSL1 : 

![image](https://user-images.githubusercontent.com/1798510/94425316-06703c00-018c-11eb-83c0-93654f075c00.png)

**Comment by MaherJendoubi** [comment]
@ant0nsc I am not sure about the version. Let me double-check it.

**Comment by ant0nsc** [comment]
To check WSL version, run `wsl -l -v` on a command prompt.

**Comment by MaherJendoubi** [comment]
It is WSL1 indeed. I apologize for saying WSL2 because I installed WSL2 but still WSL1. Thanks a lot for your help @ant0nsc and @Shruthi42

**Comment by ant0nsc** [comment]
OK to update the title of the issue to reflect that?

**Comment by MaherJendoubi** [comment]
@ant0nsc sure. done.

**Comment by MaherJendoubi** [comment]
I solved this issue with one line: wsl --set-version Ubuntu 2
