### ISSUE TITLE
"conda env remove --name InnerEye" fails because `tqdm` is overloaded

### ISSUE THREAD

**Issue by ant0nsc** [microsoft/InnerEye-DeepLearning#249]
Once the  `PYTHONPATH` is set to the repository root, it is no longer possible to remove environments (or quite possibly do anything with environments). Conda uses the `tqdm` package, and we have a hack for that at repository root to avoid further dependencies.
```
antonsc@MSR:/mnt/c/git$ conda env remove -n InnerEye
Traceback (most recent call last):
  File "/home/antonsc/miniconda2/bin/conda-env", line 6, in <module>
    from conda_env.cli.main import main
  File "/home/antonsc/miniconda2/lib/python2.7/site-packages/conda_env/cli/main.py", line 13, in <module>
    import conda.exports  # noqa
  File "/home/antonsc/miniconda2/lib/python2.7/site-packages/conda/exports.py", line 25, in <module>
    from . import plan  # NOQA
  File "/home/antonsc/miniconda2/lib/python2.7/site-packages/conda/plan.py", line 26, in <module>
    from .core.link import PrefixSetup, UnlinkLinkTransaction
  File "/home/antonsc/miniconda2/lib/python2.7/site-packages/conda/core/link.py", line 43, in <module>
    from ..resolve import MatchSpec
  File "/home/antonsc/miniconda2/lib/python2.7/site-packages/conda/resolve.py", line 9, in <module>
    from tqdm import tqdm
  File "/mnt/c/git/InnerEye-DeepLearning/tqdm.py", line 14
    def tqdm(arg: Any, *_rest: Any) -> Any:
                ^
SyntaxError: invalid syntax
```

**Comment by MaherJendoubi** [comment]
Hi @ant0nsc it works for me on WSL Ubuntu 20.04.1 LTS:
![image](https://user-images.githubusercontent.com/1798510/94409306-49bfb000-0176-11eb-8263-a7fbe1968631.png)

**Comment by ant0nsc** [comment]
@MaherJendoubi , appreciate your help :-) Does it still work once you set `export PYTHONPATH=<yourInnerEyeRepo>` ?

**Comment by MaherJendoubi** [comment]
@ant0nsc I did this previously and it still work : 

export PYTHONPATH=`pwd`
python InnerEye/ML/runner.py --model=HelloWorld

**Comment by ant0nsc** [comment]
Problem is still here:
```
(base) antonsc@MSR:/mnt/c/git/InnerEye-DeepLearning$ export PYTHONPATH=`pwd`
(base) antonsc@MSR:/mnt/c/git/InnerEye-DeepLearning$ cd ..
(base) antonsc@MSR:/mnt/c/git$ conda env remove -n foo2
Traceback (most recent call last):
  File "/home/antonsc/miniconda2/bin/conda-env", line 6, in <module>
    from conda_env.cli.main import main
  File "/home/antonsc/miniconda2/lib/python2.7/site-packages/conda_env/cli/main.py", line 13, in <module>
    import conda.exports  # noqa
  File "/home/antonsc/miniconda2/lib/python2.7/site-packages/conda/exports.py", line 25, in <module>
    from . import plan  # NOQA
  File "/home/antonsc/miniconda2/lib/python2.7/site-packages/conda/plan.py", line 26, in <module>
    from .core.link import PrefixSetup, UnlinkLinkTransaction
  File "/home/antonsc/miniconda2/lib/python2.7/site-packages/conda/core/link.py", line 43, in <module>
    from ..resolve import MatchSpec
  File "/home/antonsc/miniconda2/lib/python2.7/site-packages/conda/resolve.py", line 9, in <module>
    from tqdm import tqdm
ImportError: cannot import name tqdm
```
Fix is in PR already.

**Comment by MaherJendoubi** [comment]
I didn't succeed to reproduce it.

![image](https://user-images.githubusercontent.com/1798510/94715695-264f5d80-034e-11eb-8e68-1d3a3559369c.png)
