### ISSUE TITLE
HelloWorld not working on brand-new AML Compute Instance

### ISSUE THREAD

**Issue by csiebler** [microsoft/InnerEye-DeepLearning#318]
I'm trying to run the HelloWorld example on a brand new Azure Machine Learning Compute Instance, but it is failing:

Commands ran:

```cli
git clone https://github.com/microsoft/InnerEye-DeepLearning
cd InnerEye-DeepLearning

# Get LFS working
curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
sudo apt-get install git-lfs
git lfs install
git lfs pull

# Init Conda
conda init bash
conda env create --file environment.yml
conda activate InnerEye

# Run HelloWorld
export PYTHONPATH=`pwd`
python InnerEye/ML/runner.py --model=HelloWorld
```

The HelloWorld examples fails with:

```
Setting logging level to 20
2020-11-16T16:38:05Z INFO     rpdb is handling traps. To debug: identify the main runner.py process, then as root: kill -TRAP <process_id>; nc 127.0.0.1 4444
2020-11-16T16:38:05Z INFO     Found class HelloWorld in file /home/azureuser/InnerEye-DeepLearning/InnerEye/ML/configs/segmentation/HelloWorld.py
2020-11-16T16:38:05Z INFO     Creating the default output folder structure.
2020-11-16T16:38:05Z INFO     Running outside of AzureML.
2020-11-16T16:38:05Z INFO     All results will be written to a subfolder of the project root folder.
2020-11-16T16:38:05Z INFO     Run outputs folder: /home/azureuser/InnerEye-DeepLearning/outputs/2020-11-16T163805Z_HelloWorld
2020-11-16T16:38:05Z INFO     Logs folder: /home/azureuser/InnerEye-DeepLearning/outputs/2020-11-16T163805Z_HelloWorld/logs
2020-11-16T16:38:05Z INFO     Creating the adjusted output folder structure.
2020-11-16T16:38:05Z INFO     Running outside of AzureML.
2020-11-16T16:38:05Z INFO     All results will be written to a subfolder of the project root folder.
2020-11-16T16:38:05Z INFO     Run outputs folder: /home/azureuser/InnerEye-DeepLearning/outputs/2020-11-16T163805Z_HelloWorld
2020-11-16T16:38:05Z INFO     Logs folder: /home/azureuser/InnerEye-DeepLearning/outputs/2020-11-16T163805Z_HelloWorld/logs
2020-11-16T16:38:05Z INFO     extra_code_directory is unset
Setting logging level to 20
Setting up logging with level 20 to file /home/azureuser/InnerEye-DeepLearning/outputs/2020-11-16T163805Z_HelloWorld/logs/stdout.txt
2020-11-16T16:38:09Z INFO     Setting multiprocessing start method to 'fork'
2020-11-16T16:38:09Z INFO     Model training will use the local dataset provided in /home/azureuser/InnerEye-DeepLearning/Tests/ML/test_data
2020-11-16T16:38:09Z INFO     
Arguments:
	__center_size_param_value: None
	__dataset_data_frame_param_value: None
	__inference_stride_size_param_value: None
	__largest_connected_component_foreground_classes_param_value: None
	__min_l_rate_param_value: 0
	__model_category_param_value: ModelCategory.Segmentation
	__model_name_param_value: HelloWorld
	__overrides_param_value: None
	__use_gpu_param_value: False
	_architecture_param_value: UNet3D
	_class_weights_param_value: [0.02, 0.49, 0.49]
	_colours_param_value: [(130, 183, 14), (238, 127, 26)]
	_comparison_blob_storage_paths_param_value: None
	_crop_size_param_value: (64, 64, 64)
	_datasets_for_inference: None
	_datasets_for_training: None
	_epochs_to_test_param_value: None
	_feature_channels_param_value: [4]
	_file_system_config_param_value: <DeepLearningFileSystemConfig DeepLearningFileSystemConfig00010>
	_fill_holes_param_value: [True, True]
	_ground_truth_ids_display_names_param_value: ['region', 'region_1']
	_ground_truth_ids_param_value: ['region', 'region_1']
	_image_channels_param_value: ['channel1', 'channel2']
	_instance__params : {}
	_l_rate_multi_step_milestones_param_value: None
	_level_param_value: 50
	_local_dataset_param_value: /home/azureuser/InnerEye-DeepLearning/Tests/ML/test_data
	_local_weights_path_param_value: None
	_mask_id_param_value: mask
	_multiprocessing_start_method_param_value: MultiprocessingStartMethod.fork
	_name_param_value : HelloWorld00008
	_norm_method_param_value: PhotometricNormalizationMethod.CtWindow
	_num_dataload_workers_param_value: 0
	_num_epochs_param_value: 2
	_param_watchers   : {}
	_save_start_epoch_param_value: 1
	_save_step_epochs_param_value: 1
	_slice_exclusion_rules_param_value: []
	_start_epoch_param_value: 0
	_summed_probability_rules_param_value: []
	_tail_param_value : None
	_test_crop_size_param_value: (64, 64, 64)
	_test_diff_epochs_param_value: 1
	_test_start_epoch_param_value: 2
	_test_step_epochs_param_value: 1
	_train_batch_size_param_value: 2
	_use_mixed_precision_param_value: True
	_window_param_value: 200
	initialized       : True
	param             : <param.parameterized.Parameters object at 0x7f8f12cf0518>

2020-11-16T16:38:09Z INFO     
2020-11-16T16:38:09Z INFO     **** STARTING: Model training **********************************************************************
2020-11-16T16:38:09Z INFO     
2020-11-16T16:38:09Z INFO     Train: 3, Test: 1, and Val: 2. Total subjects: 6
2020-11-16T16:38:09Z INFO     
2020-11-16T16:38:09Z INFO     **** STARTING: Visualizing the effect of sampling random crops for training ************************
2020-11-16T16:38:09Z INFO     
2020-11-16T16:38:09Z INFO     Processing dataset (name=None)
2020-11-16T16:38:09Z INFO     Processing sample: 1
2020-11-16T16:38:11Z INFO     
2020-11-16T16:38:11Z INFO     **** FINISHED: Visualizing the effect of sampling random crops for training after 2.21 seconds *****
2020-11-16T16:38:11Z INFO     
2020-11-16T16:38:11Z INFO     Starting to read and parse the datasets.
2020-11-16T16:38:11Z INFO     Processing dataset (name=None)
2020-11-16T16:38:11Z INFO     Processing dataset (name=None)
2020-11-16T16:38:11Z INFO     Creating the data loader for the training set.
2020-11-16T16:38:11Z INFO     Creating the data loader for the validation set.
2020-11-16T16:38:11Z INFO     Finished creating the data loaders.
2020-11-16T16:38:11Z INFO     Writing model summary to: logs/model_summaries/model_log001.txt
Attempted to log scalar metric LoggingColumns.NumTrainableParameters:
506139
2020-11-16T16:38:11Z INFO     Making no adjustments to the model because no GPU was found.
2020-11-16T16:38:12Z INFO     Models are saved at /home/azureuser/InnerEye-DeepLearning/outputs/2020-11-16T163805Z_HelloWorld/checkpoints
2020-11-16T16:38:12Z INFO     Starting training
2020-11-16T16:38:12Z INFO     Starting epoch 1
2020-11-16T16:38:13Z INFO     Loaded the first minibatch of training data in 1.29 sec.
2020-11-16T16:38:14Z INFO     Epoch 1 training took 2.84 sec, of which waiting for next minibatch took 1.34 sec total. 2 minibatches in total.
2020-11-16T16:38:15Z INFO     Loaded the first minibatch of validation data in 0.09 sec.
2020-11-16T16:38:15Z INFO     Epoch 1 validation took 0.46 sec, of which waiting for next minibatch took 0.09 sec total. 1 minibatches in total.
2020-11-16T16:38:15Z INFO     Saved model checkpoint for epoch 1 to /home/azureuser/InnerEye-DeepLearning/outputs/2020-11-16T163805Z_HelloWorld/checkpoints/1_checkpoint.pth.tar
2020-11-16T16:38:15Z INFO     Starting epoch 2
2020-11-16T16:38:15Z INFO     Loaded the first minibatch of training data in 0.08 sec.
2020-11-16T16:38:17Z INFO     Epoch 2 training took 1.56 sec, of which waiting for next minibatch took 0.14 sec total. 2 minibatches in total.
2020-11-16T16:38:17Z INFO     Loaded the first minibatch of validation data in 0.09 sec.
2020-11-16T16:38:17Z INFO     Epoch 2 validation took 0.45 sec, of which waiting for next minibatch took 0.09 sec total. 1 minibatches in total.
2020-11-16T16:38:17Z INFO     Saved model checkpoint for epoch 2 to /home/azureuser/InnerEye-DeepLearning/outputs/2020-11-16T163805Z_HelloWorld/checkpoints/2_checkpoint.pth.tar
2020-11-16T16:38:17Z INFO     Finished training
2020-11-16T16:38:17Z INFO     
2020-11-16T16:38:17Z INFO     **** FINISHED: Model training after 8.68 seconds ***************************************************
2020-11-16T16:38:17Z INFO     
Attempted to log scalar metric Train epochs:
2
2020-11-16T16:38:17Z INFO     Using checkpoints from current run for epoch 2.
2020-11-16T16:38:17Z INFO     
2020-11-16T16:38:17Z INFO     **** STARTING: Registering default model ***********************************************************
2020-11-16T16:38:17Z INFO     
2020-11-16T16:38:17Z INFO     Copying folder for registration: /home/azureuser/InnerEye-DeepLearning/InnerEye
2020-11-16T16:38:17Z INFO     Copying file for registration: /home/azureuser/InnerEye-DeepLearning/setup.py to setup.py
2020-11-16T16:38:17Z INFO     Copying file for registration: /home/azureuser/InnerEye-DeepLearning/mypy_runner.py to mypy_runner.py
2020-11-16T16:38:17Z INFO     Copying file for registration: /home/azureuser/InnerEye-DeepLearning/score.py to score.py
2020-11-16T16:38:17Z INFO     Copying file for registration: /home/azureuser/InnerEye-DeepLearning/conftest.py to conftest.py
2020-11-16T16:38:17Z INFO     Copying file for registration: /home/azureuser/InnerEye-DeepLearning/outputs/2020-11-16T163805Z_HelloWorld/checkpoints/2_checkpoint.pth.tar to checkpoints/2_checkpoint.pth.tar
2020-11-16T16:38:17Z INFO     Registering the model on the workspace.
2020-11-16T16:38:17Z INFO     Could not load the run context. Logging offline
2020-11-16T16:38:17Z WARNING  Unable to retrieve the key for the Service Principal authentication (expected in environment variable 'APPLICATION_KEY' or YAML). Switching to interactive login.
2020-11-16T16:38:17Z ERROR    Model training/testing failed. Exception: 'list' object has no attribute 'subscription_id'
Traceback (most recent call last):
  File "InnerEye/ML/runner.py", line 386, in run_in_situ
    self.create_ml_runner().run()
  File "/home/azureuser/InnerEye-DeepLearning/InnerEye/ML/run_ml.py", line 317, in run
    best_epoch = self.run_inference_and_register_model(checkpoint_handler, ModelProcessing.DEFAULT)
  File "/home/azureuser/InnerEye-DeepLearning/InnerEye/ML/run_ml.py", line 339, in run_inference_and_register_model
    self.register_model_for_epoch(checkpoint_paths, model_description, model_proc)
  File "/home/azureuser/InnerEye-DeepLearning/InnerEye/ML/run_ml.py", line 512, in register_model_for_epoch
    model_proc=model_proc)
  File "/home/azureuser/InnerEye-DeepLearning/InnerEye/ML/run_ml.py", line 555, in register_segmentation_model
    workspace=self.azure_config.get_workspace(),
  File "/home/azureuser/InnerEye-DeepLearning/InnerEye/Azure/azure_config.py", line 226, in get_workspace
    resource_group=self.resource_group)
  File "/anaconda/envs/InnerEye/lib/python3.7/site-packages/azureml/core/workspace.py", line 566, in get
    subscription_id, auth=auth, resource_group=resource_group)
  File "/anaconda/envs/InnerEye/lib/python3.7/site-packages/azureml/core/workspace.py", line 645, in list
    subscription_id = subscription_tuple.subscription_id
AttributeError: 'list' object has no attribute 'subscription_id'
``` 

Somehow, it looks like it is trying to connect to the AML workspace of the Compute Instance, even though I have not configured anything. Would be to understand why this is happening, judging from the main README, this should not happen. Problem can be easily recreated with the provided commands above.

Thanks
Clemens

**Comment by csiebler** [comment]
Looks like when I edit `InnerEye-DeepLearning/InnerEye/settings.yml` and outcomment `application_id`, then it works... however, this seems like weird "out of the box" behaviour...

**Comment by ant0nsc** [comment]
Hi Clemens, smells like a bug indeed... For a repro, can you confirm how your settings.yml looks like? Did you modify it from what's the the github repo?

**Comment by ant0nsc** [comment]
@csiebler Please confirm if the latest code as of this morning still exhibits the problem.

**Comment by csiebler** [comment]
Sorry @ant0nsc, wasn't able to test it yesterday, but just gave it a quick try on a clean checkout and it works as expected:

```
2020-11-18T13:20:11Z INFO     Running outside of AzureML.
...
2020-11-18T13:21:56Z WARNING  Couldn't register model in offline mode
```

Thanks for fixing this so quickly!
