### ISSUE TITLE
Model comparision is broken

### ISSUE THREAD

**Issue by javier-alvarez** [microsoft/InnerEye-DeepLearning#335]
Model comparison is done best effort. It is failing silently for my H&N model in the latest master. Maybe this is related to our latest changes on model registration?

 **** STARTING: Comparing scores against baselines **************************************************
2020-12-06T00:33:44Z INFO     
2020-12-06T00:33:45Z INFO     Fetched run #master_1587168160_8652b587 379 from experiment master.
2020-12-06T00:33:45Z INFO     Downloading single file from run master_1587168160_8652b587: outputs/epoch_120/Test/dataset.csv -> /mnt/batch/tasks/shared/LS_root/jobs/radiomicsnn/azureml/master_1607213068_9d11c172/mounts/workspaceblobstore/azureml/master_1607213068_9d11c172/outputs/master_1587168160_8652b587/epoch_120/Test/dataset.csv
2020-12-06T00:33:45Z ERROR    Model baseline comparison failed. Exception: UserErrorException:
	Message: File with path outputs/epoch_120/Test/dataset.csv was not found,
available files include: azureml-logs/55_azureml-execution-tvmps_feb03aab2406c9d9cea6276f153ac385ea9c0a9008dc6f8bfd968edda95ffa70_p.txt,azureml-logs/65_job_prep-tvmps_feb03aab2406c9d9cea6276f153ac385ea9c0a9008dc6f8bfd968edda95ffa70_p.txt,azureml-logs/70_driver_log.txt,azureml-logs/75_job_post-tvmps_feb03aab2406c9d9cea6276f153ac385ea9c0a9008dc6f8bfd968edda95ffa70_p.txt,azureml-logs/process_info.json,azureml-logs/process_status.json,logs/azureml/143_azureml.log,logs/azureml/job_prep_azureml.log,logs/azureml/job_release_azureml.log,logs/train/events.out.tfevents.1587169688.c0f9df7c66024e1ab2ad67c012b0529c00000L,logs/val/events.out.tfevents.1587169688.c0f9df7c66024e1ab2ad67c012b0529c00000L.
	InnerException None
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "File with path outputs/epoch_120/Test/dataset.csv was not found,\navailable files include: azureml-logs/55_azureml-execution-tvmps_feb03aab2406c9d9cea6276f153ac385ea9c0a9008dc6f8bfd968edda95ffa70_p.txt,azureml-logs/65_job_prep-tvmps_feb03aab2406c9d9cea6276f153ac385ea9c0a9008dc6f8bfd968edda95ffa70_p.txt,azureml-logs/70_driver_log.txt,azureml-logs/75_job_post-tvmps_feb03aab2406c9d9cea6276f153ac385ea9c0a9008dc6f8bfd968edda95ffa70_p.txt,azureml-logs/process_info.json,azureml-logs/process_status.json,logs/azureml/143_azureml.log,logs/azureml/job_prep_azureml.log,logs/azureml/job_release_azureml.log,logs/train/events.out.tfevents.1587169688.c0f9df7c66024e1ab2ad67c012b0529c00000L,logs/val/events.out.tfevents.1587169688.c0f9df7c66024e1ab2ad67c012b0529c00000L."
    }
}
Traceback (most recent call last):
  File "/azureml-envs/azureml_090fd8ea3e629a0d40d6b4336fcaca65/lib/python3.7/site-packages/azureml/_restclient/clientbase.py", line 538, in _execute_with_arguments
    return self._call_api(func, *args_list, **kwargs)
  File "/azureml-envs/azureml_090fd8ea3e629a0d40d6b4336fcaca65/lib/python3.7/site-packages/azureml/_restclient/clientbase.py", line 236, in _call_api
    return self._execute_with_base_arguments(func, *args, **kwargs)
  File "/azureml-envs/azureml_090fd8ea3e629a0d40d6b4336fcaca65/lib/python3.7/site-packages/azureml/_restclient/clientbase.py", line 325, in _execute_with_base_arguments
    back_off, total_retry, self._logger, func, _noop_reset, *args, **kwargs)
  File "/azureml-envs/azureml_090fd8ea3e629a0d40d6b4336fcaca65/lib/python3.7/site-packages/azureml/_restclient/clientbase.py", line 345, in _execute_func_internal
    left_retry = cls._handle_retry(back_off, left_retry, total_retry, error, logger, func)
  File "/azureml-envs/azureml_090fd8ea3e629a0d40d6b4336fcaca65/lib/python3.7/site-packages/azureml/_restclient/clientbase.py", line 394, in _handle_retry
    raise error
  File "/azureml-envs/azureml_090fd8ea3e629a0d40d6b4336fcaca65/lib/python3.7/site-packages/azureml/_restclient/clientbase.py", line 343, in _execute_func_internal
    return func(*args, **kwargs)
  File "/azureml-envs/azureml_090fd8ea3e629a0d40d6b4336fcaca65/lib/python3.7/site-packages/azureml/_restclient/operations/artifact_operations.py", line 587, in get_content_information
    raise models.ErrorResponseException(self._deserialize, response)
azureml._restclient.models.error_response.ErrorResponseException: (UserError) Cannot find Artifact with ID ExperimentRun/dcid.master_1587168160_8652b587/outputs/epoch_120/Test/dataset.csv in Partition bb134313-1fb2-412e-9e15-b8c4e823023c.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/azureml-envs/azureml_090fd8ea3e629a0d40d6b4336fcaca65/lib/python3.7/site-packages/azureml/_restclient/artifacts_client.py", line 256, in download_artifact
    origin, container, path)
  File "/azureml-envs/azureml_090fd8ea3e629a0d40d6b4336fcaca65/lib/python3.7/site-packages/azureml/_restclient/workspace_client.py", line 67, in _execute_with_workspace_arguments
    return self._execute_with_arguments(func, copy.deepcopy(self._workspace_arguments), *args, **kwargs)
  File "/azureml-envs/azureml_090fd8ea3e629a0d40d6b4336fcaca65/lib/python3.7/site-packages/azureml/_restclient/clientbase.py", line 540, in _execute_with_arguments
    raise ServiceException(e)
azureml._restclient.exceptions.ServiceException: ServiceException:
	Code: 404
	Message: (UserError) Cannot find Artifact with ID ExperimentRun/dcid.master_1587168160_8652b587/outputs/epoch_120/Test/dataset.csv in Partition bb134313-1fb2-412e-9e15-b8c4e823023c.
	Details:

	Headers: {
	    "Date": "Sun, 06 Dec 2020 00:33:45 GMT",
	    "Content-Type": "application/json; charset=utf-8",
	    "Transfer-Encoding": "chunked",
	    "Connection": "keep-alive",
	    "Vary": "Accept-Encoding",
	    "Request-Context": "appId=cid-v1:6a27ce65-5555-41a3-85f7-b7a1ce31fd6b",
	    "x-ms-response-type": "error",
	    "x-ms-client-request-id": "b79602c5-925f-4df9-b9b9-9fc85c32bfb8",
	    "x-ms-client-session-id": "",
	    "X-Content-Type-Options": "nosniff",
	    "x-request-time": "0.448",
	    "Strict-Transport-Security": "max-age=15724800; includeSubDomains; preload",
	    "Content-Encoding": "gzip"
	}
	InnerException: {
    "additional_properties": {},
    "error": {
        "additional_properties": {
            "debugInfo": null
        },
        "code": "UserError",
        "severity": null,
        "message": "Cannot find Artifact with ID ExperimentRun/dcid.master_1587168160_8652b587/outputs/epoch_120/Test/dataset.csv in Partition bb134313-1fb2-412e-9e15-b8c4e823023c.",
        "message_format": null,
        "message_parameters": null,
        "reference_code": null,
        "details_uri": null,
        "target": null,
        "details": [],
        "inner_error": {
            "additional_properties": {},
            "code": "NotFoundError",
            "inner_error": null
        }
    },
    "correlation": {
        "operation": "aff948f50f49cb40bcdbddbb4fd64313",
        "request": "bc73e5cd75584a44"
    },
    "environment": "westeurope",
    "location": "westeurope",
    "time": {},
    "component_name": "artifact"
}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/batch/tasks/shared/LS_root/jobs/radiomicsnn/azureml/master_1607213068_9d11c172/mounts/workspaceblobstore/azureml/master_1607213068_9d11c172/innereye-deeplearning/InnerEye/ML/run_ml.py", line 481, in try_compare_scores_against_baselines
    compare_scores_against_baselines(self.model_config, self.azure_config, model_proc)
  File "/mnt/batch/tasks/shared/LS_root/jobs/radiomicsnn/azureml/master_1607213068_9d11c172/mounts/workspaceblobstore/azureml/master_1607213068_9d11c172/innereye-deeplearning/InnerEye/ML/baselines_util.py", line 83, in compare_scores_against_baselines
    model_metrics_df)
  File "/mnt/batch/tasks/shared/LS_root/jobs/radiomicsnn/azureml/master_1607213068_9d11c172/mounts/workspaceblobstore/azureml/master_1607213068_9d11c172/innereye-deeplearning/InnerEye/ML/baselines_util.py", line 111, in download_and_compare_scores
    comparison_baselines = get_comparison_baselines(outputs_folder, azure_config, comparison_blob_storage_paths)
  File "/mnt/batch/tasks/shared/LS_root/jobs/radiomicsnn/azureml/master_1607213068_9d11c172/mounts/workspaceblobstore/azureml/master_1607213068_9d11c172/innereye-deeplearning/InnerEye/ML/baselines_util.py", line 174, in get_comparison_baselines
    blob_path_parent / DATASET_CSV_FILE_NAME, destination_folder, run, True)
  File "/mnt/batch/tasks/shared/LS_root/jobs/radiomicsnn/azureml/master_1607213068_9d11c172/mounts/workspaceblobstore/azureml/master_1607213068_9d11c172/innereye-deeplearning/InnerEye/Azure/azure_util.py", line 397, in download_outputs_from_run
    run.download_file(blobs_root_path, str(destination), _validate_checksum=True)
  File "/azureml-envs/azureml_090fd8ea3e629a0d40d6b4336fcaca65/lib/python3.7/site-packages/azureml/core/run.py", line 50, in wrapped
    return func(self, *args, **kwargs)
  File "/azureml-envs/azureml_090fd8ea3e629a0d40d6b4336fcaca65/lib/python3.7/site-packages/azureml/core/run.py", line 1974, in download_file
    _validate_checksum)
  File "/azureml-envs/azureml_090fd8ea3e629a0d40d6b4336fcaca65/lib/python3.7/site-packages/azureml/_restclient/artifacts_client.py", line 263, in download_artifact
    self._handle_http_operation_error(operation_error, origin, container, path)
  File "/azureml-envs/azureml_090fd8ea3e629a0d40d6b4336fcaca65/lib/python3.7/site-packages/azureml/_restclient/artifacts_client.py", line 508, in _handle_http_operation_error
    "{2}.".format(type_string, path, ",".join(existing_files)))
azureml.exceptions._azureml_exception.UserErrorException: UserErrorException:
	Message: File with path outputs/epoch_120/Test/dataset.csv was not found,
available files include: azureml-logs/55_azureml-execution-tvmps_feb03aab2406c9d9cea6276f153ac385ea9c0a9008dc6f8bfd968edda95ffa70_p.txt,azureml-logs/65_job_prep-tvmps_feb03aab2406c9d9cea6276f153ac385ea9c0a9008dc6f8bfd968edda95ffa70_p.txt,azureml-logs/70_driver_log.txt,azureml-logs/75_job_post-tvmps_feb03aab2406c9d9cea6276f153ac385ea9c0a9008dc6f8bfd968edda95ffa70_p.txt,azureml-logs/process_info.json,azureml-logs/process_status.json,logs/azureml/143_azureml.log,logs/azureml/job_prep_azureml.log,logs/azureml/job_release_azureml.log,logs/train/events.out.tfevents.1587169688.c0f9df7c66024e1ab2ad67c012b0529c00000L,logs/val/events.out.tfevents.1587169688.c0f9df7c66024e1ab2ad67c012b0529c00000L.
	InnerException None
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "File with path outputs/epoch_120/Test/dataset.csv was not found,\navailable files include: azureml-logs/55_azureml-execution-tvmps_feb03aab2406c9d9cea6276f153ac385ea9c0a9008dc6f8bfd968edda95ffa70_p.txt,azureml-logs/65_job_prep-tvmps_feb03aab2406c9d9cea6276f153ac385ea9c0a9008dc6f8bfd968edda95ffa70_p.txt,azureml-logs/70_driver_log.txt,azureml-logs/75_job_post-tvmps_feb03aab2406c9d9cea6276f153ac385ea9c0a9008dc6f8bfd968edda95ffa70_p.txt,azureml-logs/process_info.json,azureml-logs/process_status.json,logs/azureml/143_azureml.log,logs/azureml/job_prep_azureml.log,logs/azureml/job_release_azureml.log,logs/train/events.out.tfevents.1587169688.c0f9df7c66024e1ab2ad67c012b0529c00000L,logs/val/events.out.tfevents.1587169688.c0f9df7c66024e1ab2ad67c012b0529c00000L."
    }
}

**Comment by ant0nsc** [comment]
- Understand where that failure comes from
- If something goes wrong with model comparison, the job should fail
- Check when we actually do the model comparison. If it fails, it should not prevent things like model registration or reporting from happening.
