### ISSUE TITLE
The sample lung segmentation throws a file not found error while trying to read the last saved checkpoint

### ISSUE THREAD

**Issue by amogh3892** [microsoft/InnerEye-DeepLearning#424]
Hi, 

I have been trying to execute the sample lung segmentation code as given in (https://github.com/microsoft/InnerEye-DeepLearning/blob/main/docs/sample_tasks.md)

Downloading and preparing the dataset completed successfully. Although, for the training purpose, I am trying to use the local GPUs instead of running it on Azure cloud. 

I replaced the following line in the segmentation config Lung.py 
azure_dataset_id="name_of_your_dataset_on_azure"

to 
local_dataset=path to the local dataset ..... 

and then tried running 
python InnerEye/ML/runner.py --azureml=False --model=Lung --train=True 

I am getting an error with respect to the reading of the checkpoint as indicated below. I assume this corresponds to the first epoch itself. I also could not find any checkpoints being saved in the path as indicated. Please help and provide inputs regarding what has to be done to solve this issue. Thank you for the help. 

2021-03-22T21:08:11Z INFO     Setting multiprocessing start method to 'fork'
2021-03-22T21:08:11Z INFO     Model training will use the local dataset provided in /mnt/rstor/CSE_BME_AXM788/home/axh672/Projects/Data/LCTSC
2021-03-22T21:08:11Z INFO     
2021-03-22T21:08:11Z INFO     **** STARTING: Model training **********************************************************************
2021-03-22T21:08:11Z INFO     
2021-03-22T21:08:11Z INFO     Number of available GPUs: 2
2021-03-22T21:08:11Z INFO     Using 2 GPUs with accelerator 'ddp'
2021-03-22T21:08:11Z INFO     LOCAL_RANK: 1 - CUDA_VISIBLE_DEVICES: [0,1]
2021-03-22T21:08:11Z INFO     Using native 16bit precision.
2021-03-22T21:08:11Z INFO     GLOBAL_RANK: None, LOCAL_RANK 1. trainer.global_rank: 0
2021-03-22T21:08:12Z INFO     Starting training
2021-03-22T21:08:12Z INFO     initializing ddp: GLOBAL_RANK: 1, MEMBER: 2/2
2021-03-22T21:08:12Z INFO     Starting to read and parse the datasets.
2021-03-22T21:08:12Z INFO     Processing dataset (name=None)
2021-03-22T21:08:12Z INFO     Processing dataset (name=None)
2021-03-22T21:08:12Z INFO     Creating the data loader for the training set.
2021-03-22T21:08:12Z INFO     Creating the data loader for the validation set.
2021-03-22T21:08:12Z INFO     Finished creating the data loaders.
2021-03-22T21:08:12Z INFO     Choosing the best checkpoint and removing redundant files.
2021-03-22T21:08:12Z INFO     Files in checkpoint folder: 
2021-03-22T21:08:12Z ERROR    Model training/testing failed. Exception: Checkpoint file last.ckpt not found. Existing files: 

[AB#3837](https://innereye.visualstudio.com/60ce1777-00d6-4015-82bc-488a0c00202f/_workitems/edit/3837)

**Comment by ant0nsc** [comment]
From these log files, it appears that the training loop actually did not run. Something should have been printed out between "Finished creating the data loaders" and "Choosing the best checkpoint". And if training does not run, there will be no checkpoint. 

Can you post the `Lung.py` configuration file that you are using?

**Comment by amogh3892** [comment]
Thank you for the quick response. Please find below the Lung.py configuration file. The only change I have made is replacing azure_dataset_id with local_dataset.


#  ------------------------------------------------------------------------------------------
#  Copyright (c) Microsoft Corporation. All rights reserved.
#  Licensed under the MIT License (MIT). See LICENSE in the repo root for license information.
#  ------------------------------------------------------------------------------------------
from typing import Any

import numpy
import pandas as pd

from InnerEye.ML.config import MixtureLossComponent, PhotometricNormalizationMethod, SegmentationLoss, \
    SegmentationModelBase, equally_weighted_classes
from InnerEye.ML.deep_learning_config import OptimizerType
from InnerEye.ML.utils.split_dataset import DatasetSplits

from pathlib import Path 
# Change this string to the name of your dataset on Azure blob storage.
AZURE_DATASET_ID = "2339eba2-8ec5-4ccb-86ff-c170470ac6e2_geonorm_with_train_test_split_2020_05_26"


class Lung(SegmentationModelBase):
    """
    Lung CT image segmentation model
    Target structures are: Esophagus, Heart, Left and Right Lungs, and Spinal cord
    """

    def __init__(self, **kwargs: Any) -> None:
        fg_classes = ["spinalcord", "lung_r", "lung_l", "heart", "esophagus"]
        fg_display_names = ["SpinalCord", "Lung_R", "Lung_L", "Heart", "Esophagus"]
        super().__init__(
            architecture="UNet3D",
            feature_channels=[32],
            kernel_size=3,
            # azure_dataset_id=AZURE_DATASET_ID,
            local_dataset=Path("/mnt/rstor/CSE_BME_AXM788/home/axh672/Projects/Data/LCTSC"),
            crop_size=(64, 224, 224),
            test_crop_size=(128, 512, 512),
            image_channels=["ct"],
            ground_truth_ids=fg_classes,
            ground_truth_ids_display_names=fg_display_names,
            colours=[(255, 255, 255)] * len(fg_classes),
            fill_holes=[False] * len(fg_classes),
            largest_connected_component_foreground_classes=["lung_r", "lung_l", "heart"],
            num_dataload_workers=8,
            norm_method=PhotometricNormalizationMethod.CtWindow,
            level=40,
            window=400,
            class_weights=equally_weighted_classes(fg_classes, background_weight=0.02),
            train_batch_size=8,
            inference_batch_size=1,
            inference_stride_size=(64, 256, 256),
            start_epoch=0,
            num_epochs=1,
            l_rate=1e-3,
            min_l_rate=1e-5,
            l_rate_polynomial_gamma=0.9,
            optimizer_type=OptimizerType.Adam,
            opt_eps=1e-4,
            adam_betas=(0.9, 0.999),
            momentum=0.9,
            weight_decay=1e-4,
            recovery_checkpoint_save_interval=1,
            use_mixed_precision=True,
            use_model_parallel=True,
            monitoring_interval_seconds=0,
            loss_type=SegmentationLoss.Mixture,
            mixture_loss_components=[MixtureLossComponent(0.5, SegmentationLoss.Focal, 0.2),
                                     MixtureLossComponent(0.5, SegmentationLoss.SoftDice, 0.1)],
        )
        self.add_and_validate(kwargs)

    def get_model_train_test_dataset_splits(self, dataset_df: pd.DataFrame) -> DatasetSplits:
        # The first 24 subject IDs are the designated test subjects in this dataset.
        test = list(map(str, range(0, 24)))
        train_val = list(dataset_df[~dataset_df.subject.isin(test)].subject.unique())

        val = list(map(str, numpy.random.choice(train_val, int(len(train_val) * 0.1), replace=False)))
        train = [str(x) for x in train_val if x not in val]

        return DatasetSplits.from_subject_ids(
            df=dataset_df,
            test_ids=test,
            val_ids=val,
            train_ids=train
        )

**Comment by ant0nsc** [comment]
Compared to what is in `main`, you also changed the `num_epochs` parameter. Try setting that to 10, and then check if you see any output in the areas that I mentioned above.

**Comment by amogh3892** [comment]
Sorry about that. I had changed to 1 epoch just to debug the error. But I am getting the same error with 10 epochs too. However, as you mentioned, this time some parameters got printed. 

Starting InnerEye runner.
2021-03-24T13:04:48Z INFO     Setting multiprocessing start method to 'fork'
2021-03-24T13:04:48Z INFO     Model training will use the local dataset provided in /mnt/rstor/CSE_BME_AXM788/home/axh672/Projects/Data/LCTSC
2021-03-24T13:04:48Z INFO
2021-03-24T13:04:48Z INFO     **** STARTING: Model training **********************************************************************
2021-03-24T13:04:48Z INFO
2021-03-24T13:04:48Z INFO     Number of available GPUs: 2
2021-03-24T13:04:48Z INFO     Using 2 GPUs with accelerator 'ddp'
LOCAL_RANK: 1 - CUDA_VISIBLE_DEVICES: [0,1]
2021-03-24T13:04:48Z INFO     LOCAL_RANK: 1 - CUDA_VISIBLE_DEVICES: [0,1]
Using native 16bit precision.
2021-03-24T13:04:48Z INFO     Using native 16bit precision.
2021-03-24T13:04:48Z INFO     GLOBAL_RANK: None, LOCAL_RANK 1. trainer.global_rank: 0
2021-03-24T13:04:49Z INFO     Starting training
initializing ddp: GLOBAL_RANK: 1, MEMBER: 2/2
2021-03-24T13:04:49Z INFO     initializing ddp: GLOBAL_RANK: 1, MEMBER: 2/2
2021-03-24T13:04:49Z INFO     Starting to read and parse the datasets.
2021-03-24T13:04:49Z INFO     Processing dataset (name=None)
2021-03-24T13:04:49Z INFO     Starting to read and parse the datasets.
2021-03-24T13:04:49Z INFO     Processing dataset (name=None)
2021-03-24T13:04:49Z INFO     Processing dataset (name=None)
2021-03-24T13:04:49Z INFO     Creating the data loader for the training set.
2021-03-24T13:04:49Z INFO     Creating the data loader for the validation set.
2021-03-24T13:04:49Z INFO     Finished creating the data loaders.
2021-03-24T13:04:49Z INFO     Processing dataset (name=None)
2021-03-24T13:04:49Z INFO     Creating the data loader for the training set.
2021-03-24T13:04:49Z INFO     Creating the data loader for the validation set.
2021-03-24T13:04:49Z INFO     Finished creating the data loaders.

  | Name         | Type                        | Params
-------------------------------------------------------------
0 | model        | UNet3D                      | 32 M
1 | loss_fn      | MixtureLoss                 | 0
2 | train_dice   | MetricForMultipleStructures | 0
3 | val_dice     | MetricForMultipleStructures | 0
4 | train_voxels | MetricForMultipleStructures | 0
5 | val_voxels   | MetricForMultipleStructures | 0
2021-03-24T13:04:51Z INFO
  | Name         | Type                        | Params
-------------------------------------------------------------
0 | model        | UNet3D                      | 32 M
1 | loss_fn      | MixtureLoss                 | 0
2 | train_dice   | MetricForMultipleStructures | 0
3 | val_dice     | MetricForMultipleStructures | 0
4 | train_voxels | MetricForMultipleStructures | 0
5 | val_voxels   | MetricForMultipleStructures | 0
2021-03-24T13:05:42Z INFO     Epoch 0 training: Loaded the first minibatch of data in 50.99 sec.
2021-03-24T13:05:43Z INFO     Terminating training thread with rank 1.
2021-03-24T13:05:44Z INFO     Choosing the best checkpoint and removing redundant files.
2021-03-24T13:05:44Z INFO     Files in checkpoint folder:
2021-03-24T13:05:44Z ERROR    Model training/testing failed. Exception: Checkpoint file last.ckpt not found. Existing files:
Traceback (most recent call last):
  File "InnerEye/ML/runner.py", line 271, in run_in_situ
    self.create_ml_runner().run()
  File "/mnt/rstor/CSE_BME_AXM788/home/axh672/hpc/innereye/InnerEye-DeepLearning/InnerEye/ML/run_ml.py", line 257, in run
    model_train(self.model_config, checkpoint_handler)
  File "/mnt/rstor/CSE_BME_AXM788/home/axh672/hpc/innereye/InnerEye-DeepLearning/InnerEye/ML/model_training.py", line 252, in model_train
    cleanup_checkpoint_folder(config.checkpoint_folder)
  File "/mnt/rstor/CSE_BME_AXM788/home/axh672/hpc/innereye/InnerEye-DeepLearning/InnerEye/ML/common.py", line 139, in cleanup_checkpoint_folder
    keep_best_checkpoint(path)
  File "/mnt/rstor/CSE_BME_AXM788/home/axh672/hpc/innereye/InnerEye-DeepLearning/InnerEye/ML/common.py", line 119, in keep_best_checkpoint
    raise FileNotFoundError(f"Checkpoint file {LAST_CHECKPOINT_FILE_NAME_WITH_SUFFIX} not found. {all_files}")
FileNotFoundError: Checkpoint file last.ckpt not found. Existing files:
Traceback (most recent call last):
  File "InnerEye/ML/runner.py", line 340, in <module>
    main()
  File "InnerEye/ML/runner.py", line 336, in main
    post_cross_validation_hook=default_post_cross_validation_hook)
  File "InnerEye/ML/runner.py", line 330, in run
    return runner.run()
  File "InnerEye/ML/runner.py", line 204, in run
    self.run_in_situ()
  File "InnerEye/ML/runner.py", line 281, in run_in_situ
    f"At least one component of the runner failed: {os.linesep} {os.linesep.join(error_messages)}")
ValueError: At least one component of the runner failed:
 Training failed: Checkpoint file last.ckpt not found. Existing files:

**Comment by ant0nsc** [comment]
From these log files, it still seems like training is terminating prematurely. I would expect a few lines that look like:
```
2021-03-19T14:41:07Z INFO     Epoch 0 training: Loaded the first minibatch of data in 0.42 sec.
2021-03-19T14:41:14Z INFO     Epoch 0 validation: Loaded the first minibatch of data in 0.33 sec.
2021-03-19T14:41:15Z INFO     Epoch 0 training took 6.86sec, of which waiting for data took 0.42 sec total.
2021-03-19T14:41:15Z INFO     Epoch 0 validation took 1.52sec, of which waiting for data took 0.33 sec total.
2021-03-19T14:41:15Z INFO     Epoch 1 training: Loaded the first minibatch of data in 0.44 sec.
2021-03-19T14:41:22Z INFO     Epoch 1 validation: Loaded the first minibatch of data in 0.28 sec.
2021-03-19T14:41:23Z INFO     Epoch 1 training took 6.60sec, of which waiting for data took 0.45 sec total.
2021-03-19T14:41:23Z INFO     Epoch 1 validation took 1.31sec, of which waiting for data took 0.28 sec total.
2021-03-19T14:41:23Z INFO     Saving latest checkpoint...
```
In your log file, it only says "Epoch 0 training", not even anything about validation. Please double-check if you have any pending changes in your repo. Other than that, I can only recommend to attach a debugger.

One thing you can also try: use `--max_num_gpus=1` on the commandline to restrict to 1 GPU - single threads are usually easier for debugging.

**Comment by ant0nsc** [comment]
Closing for now. With the present information, we can't dig any deeper.
