### ISSUE TITLE
ValueError: Model name MyModel was not found in search namespaces: ['InnerEye.ML.configs'].

### ISSUE THREAD

**Issue by Med-Rokaimi** [microsoft/InnerEye-DeepLearning#818]
### Discussed in https://github.com/microsoft/InnerEye-DeepLearning/discussions/817

<div type='discussions-op-text'>

<sup>Originally posted by **Med-Rokaimi** October 26, 2022</sup>
Hey,
I'm trying to run  Glaucoma detection model following the steps in the link
[Sample task](https://innereye-deeplearning.readthedocs.io/md/sample_tasks.html).
I set up the InnerEye-DeepLearningnner locally.
I created MyGlaucomaModel in the path (InnerEye/ML/configs), and my dataset folder is located in the same path as well.
This is the model I created:
<pre>class MyGlaucomaModel(GlaucomaPublic):
    def __init__(self) -> None:
        super().__init__()
        local_dataset=full_ml_test_data_path(),
        self.azure_dataset_id="glaucoma_detection",</pre>

When I try to run the model by this command: 
<pre>python InnerEye/ML/runner.py --model=MyGlaucomaModel</pre>
I got this error:

<pre>Starting InnerEye runner at InnerEye/ML/runner.py
Adding InnerEye folder to sys.path: /home/ai/InnerEye-DeepLearning
Setting up logging to stdout.
Setting logging level to 20 (INFO)
2022-10-26T06:26:50Z INFO     rpdb is handling traps. To debug: identify the main runner.py process, then as root: kill -TRAP <process_id>; nc 127.0.0.1 4444
2022-10-26T06:26:50Z WARNING  (from attempt to import module InnerEye.ML.configs.MyGlaucoma): name 'full_ml_test_data_path' is not defined
2022-10-26T06:26:50Z WARNING  (from attempt to import module InnerEye.ML.configs.classification.GlaucomaPublic): name 'full_ml_test_data_path' is not defined
Traceback (most recent call last):
  File "InnerEye/ML/runner.py", line 467, in <module>
    main()
  File "InnerEye/ML/runner.py", line 461, in main
    run(project_root=fixed_paths.repository_root_directory(),
  File "InnerEye/ML/runner.py", line 457, in run
    return runner.run()
  File "InnerEye/ML/runner.py", line 215, in run
    self.parse_and_load_model()
  File "InnerEye/ML/runner.py", line 164, in parse_and_load_model
    config_or_container = model_config_loader.create_model_config_from_name(model_name=azure_config.model)
  File "/home/ai/InnerEye-DeepLearning/InnerEye/ML/utils/config_loader.py", line 132, in create_model_config_from_name
    raise ValueError(
ValueError: Model name MyGlaucomaModel was not found in search namespaces: ['InnerEye.ML.configs']</pre>
Can you please help me? I</div>

[AB#7873](https://innereye.visualstudio.com/60ce1777-00d6-4015-82bc-488a0c00202f/_workitems/edit/7873)

**Comment by peterhessey** [comment]
Hi, I've managed to repeat this bug myself but I'm not sure on the exact cause yet, will take a closer look ASAP and get a bugfix to you soon :)

**Comment by Med-Rokaimi** [comment]
The error has been fixed after solving the these two warnings:
<pre>
2022-10-26T06:26:50Z WARNING  (from attempt to import module InnerEye.ML.configs.MyGlaucoma): name 'full_ml_test_data_path' is not defined
2022-10-26T06:26:50Z WARNING  (from attempt to import module InnerEye.ML.configs.classification.GlaucomaPublic): name 'full_ml_test_data_path' is not defined
</pre>
The model is not loaded because of these two warnings.
